# ------------------------------------------------------------------------------
# The deployment file considers master node also for targetting deployments
# The following command needs to be set into both master node and worker nodes
# kubectl label node k8s-master kubernetes.io/system-apis=allow
# ------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airroute-locator-app
spec:
  selector:
      matchLabels:
        app: airroute-locator-app
  replicas: 1
  template:
    metadata:
      labels:
        app: airroute-locator-app
    spec:
      nodeSelector:
        kubernetes.io/process-apis: allow
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - airroute-locator-app
            topologyKey: "kubernetes.io/hostname"
      # ----------------------------------
      # will target master node deployment
      #tolerations:
      #  - key: "node-role.kubernetes.io/master"
      #    operator: "Exists"
      #    effect: "NoSchedule"
      # ----------------------------------
      containers:
        - name: airroute-locator-app
          image: srivatsabc/airroute-locator-app:process-api-v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: RUNTIME_ENV_TYPE #In order to help mule application pickup the right jdbc properties
              valueFrom:
                configMapKeyRef:
                  name: airroute-locator-app-config
                  key: RUNTIME_ENV_TYPE
